version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Los_Angeles
    day: tuesday
  groups:
    wp-packages:
      patterns:
      - "@wordpress*"
  open-pull-requests-limit: 99
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Los_Angeles
    day: tuesday
  groups:
    php-development:
      patterns:
      - "wp-coding-standards/*"
      - "phpcompatibility/*"
      - "dealerdirect/*"
      - "sirbrillig/*"
  open-pull-requests-limit: 99
