name: PHP_CodeSniffer

on: pull_request

# The GITHUB_TOKEN used by Dependabot has read-only permissions
# by default, so we provide write permissions to this workflow
# so that comments can be left on the pull request.
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
permissions:
  contents: read
  pull-requests: write

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          tools: composer, cs2pr

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: php-dependencies-${{ hashFiles('composer.lock') }}
          restore-keys: php-dependencies-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Detect coding standard violations
        run: vendor/bin/phpcs -q --report=checkstyle . | cs2pr --graceful-warnings
